name: build and test

on:
  push:
    branches: [ main, project ]
  pull_request:
    branches: [ main, project ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Debug build
        run:  msbuild Project/dijikstra/dijikstra.sln /p:Configuration=Debug

      - name: Archive project for leak detection
        uses: actions/upload-artifact@v2
        with:
          name: dijikstra-for-valgrind
          path: Project/dijikstra/x64/Debug/dijikstra.exe

      - name: Release build
        run:  msbuild Project/dijikstra/dijikstra.sln /p:Configuration=Release
      
      - name: Setup VSTest.console.exe
        uses: darenm/Setup-VSTest@v1
      
      - name: Perform unit testing
        run:  VSTest.Console.exe Project/dijikstra/Debug/test.dll

  detect-memory-leaks:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Add valgrind
        run: sudo apt install valgrind
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: dijikstra-for-valgrind
      - name: Run valgrind
        run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt Project/dijikstra/x64/Debug/dijikstra.exe

